Tfg 32 Análisis de los datos
pablojjimenez/TFG pull request #38
Opened 2022-03-06 20:09 UTC by pablojjimenez

En esta PR añado explicación de los datos de los que disponemos. Quién me los ha proporcionado y que de que variables disponen. 
Concluimos:
- closes #35 con la creación de los dos principales modelos para la solución del problema.
- closes #37 se añade en esta PR CI; un lint para asegurar la belleza del código y test para asegurar la calidad funcional.
- closes #32 redacción de las fuentes de datos.

2022-03-07 19:27 UTC, pablojjimenez commented
Listo para revisar @JJ 😇

2022-03-09 13:02 UTC, JJ requested changes
Buen primer intento, todavía habría que darle alguna vuelta.

2022-03-09 13:02 UTC, JJ commented on scripts/run_tests.sh
> +#!/bin/bash
Agh, no, por favor. Como te he dicho antes, tienes que decidir qué gestor de tareas entre los disponibles para Python vas a usar, y documentar la decisión.
El desarrollo ágil incluye "la configuración debe estar en el entorno" y entre ellos las diferentes tareas que se vayan a hacer.

2022-03-09 13:02 UTC, JJ commented on scripts/run_tests.sh
> +. test_venv/bin/activate
No uses entornos virtuales. Una decisión nefasta en Python, que no sigue las mejores prácticas actuales. En todo caso, todo lo que decidas (incluso estos detalles) t9ienes que documentarlos.

2022-03-09 16:33 UTC, pablojjimenez commented on .github/workflows/allow_words.txt
> +Arïadna
El nombre del servidor si, el nombre de mi clase no.

2022-03-13 18:36 UTC, merged