Añado predicción
pablojjimenez/TFG pull request #66
Opened 2022-05-03 18:47 UTC by pablojjimenez

Con esta entrega termino el PMV 3 y closes #51 
Se hace uso de la biblioteca Prophet y Matplotlib para poder someramente observar como podrían avanzar los datos con el paso del tiempo.

2022-05-07 10:29 UTC, pablojjimenez commented
closes #65 porque las bibliotecas nuevas añadidas dan problemas con esas versiones de Python.

2022-05-17 18:43 UTC, JJ requested changes
El PR no tiene ningún problema gordo, pero el problema principal está en la metodología. *Siempre* tienes que trabajar con un issue, y este tiene que estar enganchado a una HU. En este caso, no has mencionado ninguno en ningún commit, por lo que es imposible saber si lo estás desarrollando correctamente.

2022-05-17 18:43 UTC, JJ commented on .github/workflows/python_ci.yaml
> +        python-version: ["3.8","3.9"]
¿Esto es que no funciona con las últimas versiones?

2022-05-17 18:43 UTC, JJ commented on code/repositories/raziel_repository.py
> +    def prepare_and_gruping_dataframe(self, params: ListParams, var1: str, var2: str):
typo: grouping

2022-05-17 18:43 UTC, JJ commented on code/repositories/raziel_repository.py
> +        for i in [6, 7, 8, 9, 10, 11, 12, 13, 14]:
`range(6,14)`

2022-05-17 18:43 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Para realizar pequeñas predicciones basadas en series temporales he decidido utilizar la biblioteca Prophet que es open source y es mantenida por el equipo de Meta. Está disponible tanto en Python co
Nunca digas "he decidido". Siempre tienes que decir
* Qué requisitos buscas
* Qué opciones hay
* Cómo cumplen las diferentes opciones esos requisitos.

2022-05-17 18:44 UTC, JJ commented
Tampoco se suelen cerrar las HUs desde un issue; sólo se cierran issues.

2022-05-17 18:46 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +\item Precisa y rápida: Los modelos se ajustan usando Stan, otra biblioteca de inferencia estadística bayesiana con estimación de verosimilitud penalizada.
Estos serían los requisitos, pero no tienes que ponerlos como descripción ni como "venta" de lo que has elegido, sino que tienen que venir antes.
Recuerda que una de las rúbricas es "analiza lo existente y toma decisiones informadas" o algo así.

2022-05-17 20:45 UTC, pablojjimenez commented on .github/workflows/python_ci.yaml
> +        python-version: ["3.8","3.9"]
Efectivamente, esto si viene reflejado en su commit https://github.com/pablojjimenez/TFG/pull/66/commits/fddd1f41cda58662a30d7b5cf8c2438d658fc6ee

2022-05-17 20:45 UTC, pablojjimenez commented on doc/secciones/06_implementacion.tex
> +Para realizar pequeñas predicciones basadas en series temporales he decidido utilizar la biblioteca Prophet que es open source y es mantenida por el equipo de Meta. Está disponible tanto en Python co
Cierto, gracias por el _reminder_

2022-05-17 20:46 UTC, pablojjimenez commented on doc/secciones/06_implementacion.tex
> +\item Precisa y rápida: Los modelos se ajustan usando Stan, otra biblioteca de inferencia estadística bayesiana con estimación de verosimilitud penalizada.
Okey, voy a darle una vuelta...

2022-05-19 15:29 UTC, JJ commented on .github/workflows/python_ci.yaml
> +        python-version: ["3.8","3.9"]
Ya me imaginaba algo así, pero ¿por qué eliminas la 3.10? Eliminar las últimas versiones siempre es peligroso, porque puede hacer que acabe deprecándose en no mucho tiempo.

2022-05-22 17:43 UTC, merged

2022-05-23 16:44 UTC, JJ commented
> closes #65 porque las bibliotecas nuevas añadidas dan problemas con esas versiones de Python.

Esto tendrías que haberlo puesto en el body. Pero el commit, al fusionarlo, debería haber funcionado.

2022-06-16 08:29 UTC, JJ commented on .github/workflows/python_ci.yaml
> +        python-version: ["3.8","3.9"]
No has contestado a esto todavía... No funcionar en las últimas versiones es un problema.