TFG-73 Add configuration and deletion of residues
pablojjimenez/TFG pull request #77
Opened 2022-06-14 19:23 UTC by pablojjimenez

Con esta entrega avanzo en la HU #72 y mejoro la PR #71 

Para evitar utilizar constante en el código y poder aplicarle al código distintas configuraciones he implementado un mecanismo de configuración distribuida. closes #73

Además, se soluciona el problema que suponía la realización de peticiones continudas  a la generación de imágenes, de forma que ahora generamos un nombre único por cada imagen que pide el usuario, de esta forma nunca se podrán intercambiar. Se hace uso del directorio temporal del sistema `/tmp`. closes #75

2022-06-16 08:46 UTC, JJ requested changes
El principal problema es que sigues sin evitar condiciones de carrera. Y que deberías encapsular la configuración en un objeto.

2022-06-16 08:46 UTC, JJ commented on code/config/general_config.py
> +HOST = os.getenv('HOST', '0.0.0.0')
Bastante más flexible si usas una clase que importes y puedas pasar como parámetro.
Tampoco estás usando configuración distribuida, así que simplemente no lo pongas en el título.

2022-06-16 08:46 UTC, JJ commented on code/main.py
> +from config.general_config import HOST, PORT, DEBUG_APP
Si usas una clase u objeto no tienes que importar todas por separado.

2022-06-16 08:46 UTC, JJ commented on code/main.py
> +    uvicorn.run("app:app", host=HOST, port=PORT, reload=DEBUG_APP)
Tampoco entiendo muy bien por qué no pones esto en una orden de `invoke`. Ni por qué no usas `invoke`. Toda aplicación tiene que tener un gestor de tareas, e `invoke` parece ser el más aceptado (pero tendrás que mirar cuales hay en concreto)

2022-06-16 08:46 UTC, JJ commented on code/managers/predictor_manager.py
> +    CHART_PATH = CHARTS_BASE_PATH
¿Por qué no usas la otra variable?

2022-06-16 08:46 UTC, JJ commented on code/managers/predictor_manager.py
> +    CHART_PATH = CHARTS_BASE_PATH
Y, de veras, no puedes poner un path en el repo, ni siempre el mismo. Una vez más, sigue las mejores prácticas para evitar condiciones de carrera.

2022-06-18 07:49 UTC, pablojjimenez commented on code/main.py
> +from config.general_config import HOST, PORT, DEBUG_APP
Hecho!

2022-06-22 16:19 UTC, JJ approved these changes
Son cambios de detalle. Lo de evitar condiciones de carrera todavía es esencial, pero no es parte de este PR, creo. la solución de borrar ficheros temporales no es buena, porque sigue sin tener en cuenta que pueden llegar dos peticiones a la vez y las dos van a ir al mismo fichero.
Deberías tener tests de integración que probaran eso, hacer dos peticiones una detrás de otra que comprueben que no se mezclan.

2022-06-22 16:19 UTC, JJ commented on code/main.py
> +    uvicorn.run("app:app", host=config.host, port=config.port, reload=config.debug_app)
Esto debería ir en un script de despliegue.

2022-06-22 16:19 UTC, JJ commented on code/managers/utils.py
> +def remove_pasts_images():
*past*

2022-06-22 16:19 UTC, JJ commented on doc/secciones/06_implementacion.tex
>  \subsection{Lenguaje de programación}
Siempre primero los criterios, luego la elección.

2022-06-22 19:02 UTC, pablojjimenez commented on code/main.py
> +    uvicorn.run("app:app", host=config.host, port=config.port, reload=config.debug_app)
Cuando haga esa tarea lo haré correctamente

2022-06-22 19:20 UTC, merged