TFG-74 Add http error codes
pablojjimenez/TFG pull request #81
Opened 2022-06-16 10:13 UTC by pablojjimenez

Esta entrega contribnuye a la tarea #63 (se fusionará en esa PR abierta, #71) y en consecuenta a la HU #62

Añado la captura de excepciones en los endpoints de forma que el usuario al utilzar el API esté informado de los posibles casos de error. closes #74

2022-06-21 18:41 UTC, JJ requested changes
No acabo de entender muy bien el modelo de datos, quizás porque fusionaste una serie de PRs que no tuve tiempo de ver. Pero el problema es que no tengo muy claro que estés haciendo lo que yo creía que estabas haciendo, que es fusionar los datos de los diferentes repos.

2022-06-21 18:41 UTC, JJ commented on code/app.py
> +            "code": ex.status_code
ex.status_code es un código HTTP?

2022-06-21 18:41 UTC, JJ commented on code/services/disease_service.py
> +    except (NoCorrectColumnsException, IncorrectQueryException) as e:
*Naming nit* "Incorrect", no "NoCorrect" (el resto igual)

2022-06-21 18:41 UTC, JJ commented on code/services/disease_service.py
>  @dataRouter.post("/raziel")
A ver si lo he entendido bien.
Pones rutas por cada repo. O sea, que al final lo que haces es simplemente reproducir lo que cada repo dice. No haces ningún intento de fusión de los datos de todos los repositorios, o de enriquecer uno con otro, ¿es correcto?

2022-06-21 20:40 UTC, pablojjimenez commented on code/app.py
> +            "code": ex.status_code
Sí

2022-06-22 15:27 UTC, JJ requested changes
Aunque no es estrictamente de este PR, mira el tema de los directorios temporales (o lo que sean).

2022-06-22 15:27 UTC, JJ commented on code/managers/graphic_manager.py
>          ensure_directory_exists('opt/')
¿Este es un directorio temporal para almacenar algo?
1. No lo hagas. Puedes almacenar información en memoria.
2. Si lo haces, tienes que ser fuera del espacio donde está el servicio. Eso lo abre a todo tipo de condiciones de carrera y huecos de seguridad (ya te lo dije en algún otro sitio)

2022-06-22 15:27 UTC, JJ commented on code/managers/graphic_manager.py
>          ensure_directory_exists('opt/')
Y mucho menos, usar el mismo literal en varios sitios. NUNCA se usan literales en el código.

2022-06-22 17:40 UTC, pablojjimenez commented on code/managers/graphic_manager.py
>          ensure_directory_exists('opt/')
Se resuelve en otra PR #77

2022-06-22 18:08 UTC, merged