RFG-92 Add deployment process
pablojjimenez/TFG pull request #93
Opened 2022-06-25 16:18 UTC by pablojjimenez

Con esta entrega avanzo en la HU #42 y closes #92 

- Se eliminan dependencias redundantes que a la hora de crear el contenedor docker daba poroblemas.
- Se añade el `Dockerfile` que crea el contenedor para desplegar.
- Se documenta el proceso en la memoria.

2022-06-26 17:49 UTC, JJ requested changes
Falta:
* Justificación
* Que sigas buenas prácticas en diseño del contenedor

2022-06-26 17:49 UTC, JJ commented on code/Dockerfile
> +FROM python:3.8-slim AS base
Recuerda que tienes que justificar también qué usas como base. No la pongas simplemente de forma arbitraria.

2022-06-26 17:49 UTC, JJ commented on code/Dockerfile
> +EXPOSE $PORT
Esto realmente no lo necesitas hacer si no usas Docker compose. Son simplemente metadatos, no tienen ninguna funcionalidad.

2022-06-26 17:49 UTC, JJ commented on code/Dockerfile
> +COPY . /.
No debes hacer esto NUNCA. ¡Estás copiando hasta la memoria!

2022-06-26 17:49 UTC, JJ commented on code/Dockerfile
> +RUN python -m venv /venv
Tampoco te sirve esto para nada. ¿Por qué lo haces? No te hace falta el entorno virtual si es el único programa que tienes.

2022-06-26 17:49 UTC, JJ commented on code/Dockerfile
> +CMD uvicorn app:app --host $HOST --port $PORT
¿Lanzas una sola instancia?

2022-06-26 18:19 UTC, pablojjimenez commented on code/Dockerfile
> +COPY . /.
Cierto 🤯

2022-06-26 18:31 UTC, pablojjimenez commented on code/Dockerfile
> +COPY . /.
No, la memoria no se está copiando. Estoy copiando todo el directorio `/code` incluyendo los _assets_ con los datos.

2022-06-28 15:24 UTC, JJ requested changes
Principal problema sigue siendo el COPY . . El resto son cuestiones de detalle.

2022-06-28 15:24 UTC, JJ commented on code/Dockerfile
> +COPY . /.
¿Necesitas copiar el Dockerfile dentro del contenedor  Docker? ¿Y cualquier temporal que tengas por ahí? ¿No?
COPY . siempre es una mala práctica, y un posible hueco de seguridad. Se copia sólo lo que se necesita, y estrictamente eso.

2022-06-28 15:24 UTC, JJ commented on doc/secciones/04_planificacion.tex
>      \item MacBook Pro [amortizado 5 años]: 240€
Pon el coste total, y en qué año estás, y cuanto tiempo lo has usado.

2022-06-28 15:24 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +A la hora de elegir un entorno cloud tenemos distintos de cloud computing, dependiendo de las partes de la infraestructura local que puedas gestionar.
Reescribe esto, y sé más concreto diciendo por qué eliges un PaaS. REcuerda que siempre tienes que poner primero los requisitos, luego los candidatos, luego la elección.

2022-06-28 15:24 UTC, JJ commented on doc/secciones/06_implementacion.tex
> +Para poder desplegar una aplicación en Heroku, es necesario acceder al panel de
Esto no debes ponerlo, pero si lo pones, especifica que se puede hacer desde la línea de órdenes. Todo lo que sea manual es "caro".

2022-06-28 16:42 UTC, pablojjimenez commented on doc/secciones/04_planificacion.tex
>      \item MacBook Pro [amortizado 5 años]: 240€
He creado issue para solucionarlo fuera de esta PR que es de infra para el despliegue fundamentalmente, gracias por recordármelo.

2022-06-29 16:16 UTC, merged